version: "1.0"

services:
  foodie:
    build: ./foodie
    image: foodie

    restart: unless-stopped
    env_file: ./.env

    networks:
      - backend
    ports:
      - 8080:8080

  foodie-ui:
    image: foodie-ui
    build:
      context: ./foodie-ui
    restart: unless-stopped
    env_file: ./.env
    networks:
      - frontend
    ports:
      - 3000:3000
networks:
  backend:
  frontend:
